export const countries = [
  { value: "us", label: "United States" },
  { value: "uk", label: "United Kingdom" },
  { value: "ca", label: "Canada" },
  { value: "au", label: "Australia" },
  { value: "de", label: "Germany" },
  { value: "fr", label: "France" },
  { value: "es", label: "Spain" },
  { value: "it", label: "Italy" },
  { value: "jp", label: "Japan" },
  { value: "cn", label: "China" },
  { value: "in", label: "India" },
  { value: "br", label: "Brazil" },
  { value: "mx", label: "Mexico" },
  { value: "za", label: "South Africa" },
  { value: "sg", label: "Singapore" },
  { value: "ae", label: "United Arab Emirates" },
]

export const countryCodeMap = {
  US: { code: "+1", short: "US", label: "United States" },
  UK: { code: "+44", short: "GB", label: "United Kingdom" },
  CA: { code: "+1", short: "CA", label: "Canada" },
  AU: { code: "+61", short: "AU", label: "Australia" },
  DE: { code: "+49", short: "DE", label: "Germany" },
  FR: { code: "+33", short: "FR", label: "France" },
  ES: { code: "+34", short: "ES", label: "Spain" },
  IT: { code: "+39", short: "IT", label: "Italy" },
  JP: { code: "+81", short: "JP", label: "Japan" },
  CN: { code: "+86", short: "CN", label: "China" },
  IN: { code: "+91", short: "IN", label: "India" },
  BR: { code: "+55", short: "BR", label: "Brazil" },
  MX: { code: "+52", short: "MX", label: "Mexico" },
  ZA: { code: "+27", short: "ZA", label: "South Africa" },
  SG: { code: "+65", short: "SG", label: "Singapore" },
  AE: { code: "+971", short: "AE", label: "United Arab Emirates" },
};
