const countries =[
    {
        "name": "Pakistan",
        "flag": "🇵🇰",
        "code": "PK",
        "dial_code": "+92",
        "currency": "PKR"
      },      
{ "name": "Afghanistan", "flag": "🇦🇫", "code": "AF", "dial_code": "+93", "currency": "AFN" },
{ "name": "Åland Islands", "flag": "🇦🇽", "code": "AX", "dial_code": "+358", "currency": "EUR" },
{ "name": "Albania", "flag": "🇦🇱", "code": "AL", "dial_code": "+355", "currency": "ALL" },
{ "name": "Algeria", "flag": "🇩🇿", "code": "DZ", "dial_code": "+213", "currency": "DZD" },
{ "name": "American Samoa", "flag": "🇦🇸", "code": "AS", "dial_code": "+1684", "currency": "USD" },
{ "name": "Andorra", "flag": "🇦🇩", "code": "AD", "dial_code": "+376", "currency": "EUR" },
{ "name": "Angola", "flag": "🇦🇴", "code": "AO", "dial_code": "+244", "currency": "AOA" },
{ "name": "Anguilla", "flag": "🇦🇮", "code": "AI", "dial_code": "+1264", "currency": "XCD" },
{ "name": "Antarctica", "flag": "🇦🇶", "code": "AQ", "dial_code": "+672", "currency": "AUD" },
{ "name": "Antigua and Barbuda", "flag": "🇦🇬", "code": "AG", "dial_code": "+1268", "currency": "XCD" },
{ "name": "Argentina", "flag": "🇦🇷", "code": "AR", "dial_code": "+54", "currency": "ARS" },
{ "name": "Armenia", "flag": "🇦🇲", "code": "AM", "dial_code": "+374", "currency": "AMD" },
{ "name": "Aruba", "flag": "🇦🇼", "code": "AW", "dial_code": "+297", "currency": "AWG" },
{ "name": "Australia", "flag": "🇦🇺", "code": "AU", "dial_code": "+61", "currency": "AUD" },
{ "name": "Austria", "flag": "🇦🇹", "code": "AT", "dial_code": "+43", "currency": "EUR" },
{ "name": "Azerbaijan", "flag": "🇦🇿", "code": "AZ", "dial_code": "+994", "currency": "AZN" },
{ "name": "Bahamas", "flag": "🇧🇸", "code": "BS", "dial_code": "+1242", "currency": "BSD" },
{ "name": "Bahrain", "flag": "🇧🇭", "code": "BH", "dial_code": "+973", "currency": "BHD" },
        
        
{ "name": "Bangladesh", "flag": "🇧🇩", "code": "BD", "dial_code": "+880", "currency": "BDT" },
{ "name": "Barbados", "flag": "🇧🇧", "code": "BB", "dial_code": "+1246", "currency": "BBD" },
{ "name": "Belarus", "flag": "🇧🇾", "code": "BY", "dial_code": "+375", "currency": "BYN" },
{ "name": "Belgium", "flag": "🇧🇪", "code": "BE", "dial_code": "+32", "currency": "EUR" },
{ "name": "Belize", "flag": "🇧🇿", "code": "BZ", "dial_code": "+501", "currency": "BZD" },
{ "name": "Benin", "flag": "🇧🇯", "code": "BJ", "dial_code": "+229", "currency": "XOF" },
{ "name": "Bermuda", "flag": "🇧🇲", "code": "BM", "dial_code": "+1441", "currency": "BMD" },
{ "name": "Bhutan", "flag": "🇧🇹", "code": "BT", "dial_code": "+975", "currency": "BTN" },
{ "name": "Bolivia, Plurinational State of Bolivia", "flag": "🇧🇴", "code": "BO", "dial_code": "+591", "currency": "BOB" },
{ "name": "Bosnia and Herzegovina", "flag": "🇧🇦", "code": "BA", "dial_code": "+387", "currency": "BAM" },
{ "name": "Botswana", "flag": "🇧🇼", "code": "BW", "dial_code": "+267", "currency": "BWP" },
{ "name": "Bouvet Island", "flag": "🇧🇻", "code": "BV", "dial_code": "+47", "currency": "NOK" },
{ "name": "Brazil", "flag": "🇧🇷", "code": "BR", "dial_code": "+55", "currency": "BRL" },
{ "name": "British Indian Ocean Territory", "flag": "🇮🇴", "code": "IO", "dial_code": "+246", "currency": "USD" },
{ "name": "Brunei Darussalam", "flag": "🇧🇳", "code": "BN", "dial_code": "+673", "currency": "BND" },
{ "name": "Bulgaria", "flag": "🇧🇬", "code": "BG", "dial_code": "+359", "currency": "BGN" },
{ "name": "Burkina Faso", "flag": "🇧🇫", "code": "BF", "dial_code": "+226", "currency": "XOF" },
{ "name": "Burundi", "flag": "🇧🇮", "code": "BI", "dial_code": "+257", "currency": "BIF" },
{ "name": "Cambodia", "flag": "🇰🇭", "code": "KH", "dial_code": "+855", "currency": "KHR" },
{ "name": "Cameroon", "flag": "🇨🇲", "code": "CM", "dial_code": "+237", "currency": "FCFA" },
{ "name": "Canada", "flag": "🇨🇦", "code": "CA", "dial_code": "+1", "currency": "CAD" },
{ "name": "Cape Verde", "flag": "🇨🇻", "code": "CV", "dial_code": "+238", "currency": "CVE" },
{ "name": "Cayman Islands", "flag": "🇰🇾", "code": "KY", "dial_code": "+345", "currency": "KYD" },
{ "name": "Central African Republic", "flag": "🇨🇫", "code": "CF", "dial_code": "+236", "currency": "CAF" },
{ "name": "Chad", "flag": "🇹🇩", "code": "TD", "dial_code": "+235", "currency": "CDF" },
{ "name": "Chile", "flag": "🇨🇱", "code": "CL", "dial_code": "+56", "currency": "CLP" },
        
        
{ "name": "China", "flag": "🇨🇳", "code": "CN", "dial_code": "+86", "currency": "CNY" },
{ "name": "Christmas Island", "flag": "🇨🇽", "code": "CX", "dial_code": "+61", "currency": "AUD" },
{ "name": "Cocos (Keeling) Islands", "flag": "🇨🇨", "code": "CC", "dial_code": "+61", "currency": "AUD" },
{ "name": "Colombia", "flag": "🇨🇴", "code": "CO", "dial_code": "+57", "currency": "COP" },
{ "name": "Comoros", "flag": "🇰🇲", "code": "KM", "dial_code": "+269", "currency": "KMF" },
{ "name": "Congo", "flag": "🇨🇬", "code": "CG", "dial_code": "+242", "currency": "CDF" },
{ "name": "Congo, The Democratic Republic of the Congo", "flag": "🇨🇩", "code": "CD", "dial_code": "+243", "currency": "CDF" },
{ "name": "Cook Islands", "flag": "🇨🇰", "code": "CK", "dial_code": "+682", "currency": "NZD" },
{ "name": "Costa Rica", "flag": "🇨🇷", "code": "CR", "dial_code": "+506", "currency": "CRC" },
{ "name": "Cote d'Ivoire", "flag": "🇨🇮", "code": "CI", "dial_code": "+225", "currency": "XOF" },
{ "name": "Croatia", "flag": "🇭🇷", "code": "HR", "dial_code": "+385", "currency": "HRK" },
{ "name": "Cuba", "flag": "🇨🇺", "code": "CU", "dial_code": "+53", "currency": "CUP" },
{ "name": "Cyprus", "flag": "🇨🇾", "code": "CY", "dial_code": "+357", "currency": "CYP" },
{ "name": "Czech Republic", "flag": "🇨🇿", "code": "CZ", "dial_code": "+420", "currency": "CZK" },
{ "name": "Denmark", "flag": "🇩🇰", "code": "DK", "dial_code": "+45", "currency": "DKK" },
{ "name": "Djibouti", "flag": "🇩🇯", "code": "DJ", "dial_code": "+253", "currency": "DJF" },
{ "name": "Dominica", "flag": "🇩🇲", "code": "DM", "dial_code": "+1767", "currency": "XCD" },
{ "name": "Dominican Republic", "flag": "🇩🇴", "code": "DO", "dial_code": "+1849", "currency": "DOP" },
{ "name": "Ecuador", "flag": "🇪🇨", "code": "EC", "dial_code": "+593", "currency": "USD" },
{ "name": "Egypt", "flag": "🇪🇬", "code": "EG", "dial_code": "+20", "currency": "EGP" },
{ "name": "El Salvador", "flag": "🇸🇻", "code": "SV", "dial_code": "+503", "currency": "SVC" },
{ "name": "Equatorial Guinea", "flag": "🇬🇶", "code": "GQ", "dial_code": "+240", "currency": "GNF" },
{ "name": "Eritrea", "flag": "🇪🇷", "code": "ER", "dial_code": "+291", "currency": "ERN" },
{ "name": "Estonia", "flag": "🇪🇪", "code": "EE", "dial_code": "+372", "currency": "EEK" },
{ "name": "Ethiopia", "flag": "🇪🇹", "code": "ET", "dial_code": "+251", "currency": "ETB" },
{ "name": "Falkland Islands (Malvinas)", "flag": "🇫🇰", "code": "FK", "dial_code": "+500", "currency": "FKP" },
{ "name": "Faroe Islands", "flag": "🇫🇴", "code": "FO", "dial_code": "+298", "currency": "DKK" },
{ "name": "Fiji", "flag": "🇫🇯", "code": "FJ", "dial_code": "+679", "currency": "FJD" },
{ "name": "Finland", "flag": "🇫🇮", "code": "FI", "dial_code": "+358", "currency": "EUR" },
{ "name": "France", "flag": "🇫🇷", "code": "FR", "dial_code": "+33", "currency": "EUR" },
{ "name": "French Guiana", "flag": "🇬🇫", "code": "GF", "dial_code": "+594", "currency": "EUR" },
        
{ "name": "French Polynesia", "flag": "🇵🇫", "code": "PF", "dial_code": "+689", "currency": "XPF" },
{ "name": "French Southern Territories", "flag": "🇹🇫", "code": "TF", "dial_code": "+262", "currency": "EUR" },
{ "name": "Gabon", "flag": "🇬🇦", "code": "GA", "dial_code": "+241", "currency": "GAB" },
{ "name": "Gambia", "flag": "🇬🇲", "code": "GM", "dial_code": "+220", "currency": "GMD" },
{ "name": "Georgia", "flag": "🇬🇪", "code": "GE", "dial_code": "+995", "currency": "GEL" },
{ "name": "Germany", "flag": "🇩🇪", "code": "DE", "dial_code": "+49", "currency": "EUR" },
{ "name": "Ghana", "flag": "🇬🇭", "code": "GH", "dial_code": "+233", "currency": "GHS" },
{ "name": "Gibraltar", "flag": "🇬🇮", "code": "GI", "dial_code": "+350", "currency": "GIP" },
{ "name": "Greece", "flag": "🇬🇷", "code": "GR", "dial_code": "+30", "currency": "EUR" },
{ "name": "Greenland", "flag": "🇬🇱", "code": "GL", "dial_code": "+299", "currency": "DKK" },
{ "name": "Grenada", "flag": "🇬🇩", "code": "GD", "dial_code": "+1473", "currency": "XCD" },
{ "name": "Guadeloupe", "flag": "🇬🇵", "code": "GP", "dial_code": "+590", "currency": "EUR" },
{ "name": "Guam", "flag": "🇬🇺", "code": "GU", "dial_code": "+1671", "currency": "USD" },
{ "name": "Guatemala", "flag": "🇬🇹", "code": "GT", "dial_code": "+502", "currency": "GTQ" },
{ "name": "Guernsey", "flag": "🇬🇬", "code": "GG", "dial_code": "+44", "currency": "GBP" },
{ "name": "Guinea", "flag": "🇬🇳", "code": "GN", "dial_code": "+224", "currency": "GNF" },
{ "name": "Guinea-Bissau", "flag": "🇬🇼", "code": "GW", "dial_code": "+245", "currency": "GNF" },
{ "name": "Guyana", "flag": "🇬🇾", "code": "GY", "dial_code": "+592", "currency": "GYD" },
{ "name": "Haiti", "flag": "🇭🇹", "code": "HT", "dial_code": "+509", "currency": "HTG" },
{ "name": "Heard Island and McDonald Islands", "flag": "🇭🇲", "code": "HM", "dial_code": "+672", "currency": "AUD" },
{ "name": "Holy See (Vatican City State)", "flag": "🇻🇦", "code": "VA", "dial_code": "+379", "currency": "EUR" },
{ "name": "Honduras", "flag": "🇭🇳", "code": "HN", "dial_code": "+504", "currency": "HNL" },
{ "name": "Hong Kong", "flag": "🇭🇰", "code": "HK", "dial_code": "+852", "currency": "HKD" },
{ "name": "Hungary", "flag": "🇭🇺", "code": "HU", "dial_code": "+36", "currency": "HUF" },
{ "name": "Iceland", "flag": "🇮🇸", "code": "IS", "dial_code": "+354", "currency": "ISK" },
{ "name": "India", "flag": "🇮🇳", "code": "IN", "dial_code": "+91", "currency": "INR" },
{ "name": "Indonesia", "flag": "🇮🇩", "code": "ID", "dial_code": "+62", "currency": "IDR" },
{ "name": "Iran, Islamic Republic of Persia", "flag": "🇮🇷", "code": "IR", "dial_code": "+98", "currency": "IRR" },
{ "name": "Iraq", "flag": "🇮🇶", "code": "IQ", "dial_code": "+964", "currency": "IQD" },
{ "name": "Ireland", "flag": "🇮🇪", "code": "IE", "dial_code": "+353", "currency": "EUR" },
{ "name": "Isle of Man", "flag": "🇮🇲", "code": "IM", "dial_code": "+44", "currency": "GBP" },
{ "name": "Israel", "flag": "🇮🇱", "code": "IL", "dial_code": "+972", "currency": "ILS" },
{ "name": "Italy", "flag": "🇮🇹", "code": "IT", "dial_code": "+39", "currency": "EUR" },
{ "name": "Jamaica", "flag": "🇯🇲", "code": "JM", "dial_code": "+1876", "currency": "JMD" },
{ "name": "Japan", "flag": "🇯🇵", "code": "JP", "dial_code": "+81", "currency": "JPY" },
{ "name": "Jersey", "flag": "🇯🇪", "code": "JE", "dial_code": "+44", "currency": "GBP" },
{ "name": "Jordan", "flag": "🇯🇴", "code": "JO", "dial_code": "+962", "currency": "JOD" },
{ "name": "Kazakhstan", "flag": "🇰🇿", "code": "KZ", "dial_code": "+7", "currency": "KZT" },
{ "name": "Kenya", "flag": "🇰🇪", "code": "KE", "dial_code": "+254", "currency": "KES" },
{ "name": "Kiribati", "flag": "🇰🇮", "code": "KI", "dial_code": "+686", "currency": "AUD" },
{ "name": "Korea, Democratic People's Republic of Korea", "flag": "🇰🇵", "code": "KP", "dial_code": "+850", "currency": "KPW" },
{ "name": "Korea, Republic of South Korea", "flag": "🇰🇷", "code": "KR", "dial_code": "+82", "currency": "KRW" },
{ "name": "Kosovo", "flag": "🇽🇰", "code": "XK", "dial_code": "+383", "currency": "RSD" },
{ "name": "Kuwait", "flag": "🇰🇼", "code": "KW", "dial_code": "+965", "currency": "KWD" },
{ "name": "Kyrgyzstan", "flag": "🇰🇬", "code": "KG", "dial_code": "+996", "currency": "KGS" },
{ "name": "Laos", "flag": "🇱🇦", "code": "LA", "dial_code": "+856", "currency": "LAK" },
{ "name": "Latvia", "flag": "🇱🇻", "code": "LV", "dial_code": "+371", "currency": "EUR" },
{ "name": "Lebanon", "flag": "🇱🇧", "code": "LB", "dial_code": "+961", "currency": "LBP" },
{ "name": "Lesotho", "flag": "🇱🇸", "code": "LS", "dial_code": "+266", "currency": "LSL" },
{ "name": "Liberia", "flag": "🇱🇷", "code": "LR", "dial_code": "+231", "currency": "LRD" },
        
{ "name": "Libyan Arab Jamahiriya", "flag": "🇱🇾", "code": "LY", "dial_code": "+218", "currency": "Libyan dinar (LYD)" },
{ "name": "Liechtenstein", "flag": "🇱🇮", "code": "LI", "dial_code": "+423", "currency": "Swiss franc (CHF)" },
{ "name": "Lithuania", "flag": "🇱🇹", "code": "LT", "dial_code": "+370", "currency": "Euro (EUR)" },
{ "name": "Luxembourg", "flag": "🇱🇺", "code": "LU", "dial_code": "+352", "currency": "Euro (EUR)" },
{ "name": "Macao", "flag": "🇲🇴", "code": "MO", "dial_code": "+853", "currency": "Macanese pataca (MOP)" },
{ "name": "Macedonia", "flag": "🇲🇰", "code": "MK", "dial_code": "+389", "currency": "Macedonian denar (MKD)" },
{ "name": "Madagascar", "flag": "🇲🇬", "code": "MG", "dial_code": "+261", "currency": "Malagasy ariary (MGA)" },
{ "name": "Malawi", "flag": "🇲🇼", "code": "MW", "dial_code": "+265", "currency": "Malawian kwacha (MWK)" },
{ "name": "Malaysia", "flag": "🇲🇾", "code": "MY", "dial_code": "+60", "currency": "Malaysian ringgit (MYR)" },
{ "name": "Maldives", "flag": "🇲🇻", "code": "MV", "dial_code": "+960", "currency": "Maldivian rufiyaa (MVR)" },
        
        
{ "name": "Seychelles", "flag": "🇸🇨", "code": "SC", "dial_code": "+248", "currency": "Seychellois rupee (SCR)" },
{ "name": "Sierra Leone", "flag": "🇸🇱", "code": "SL", "dial_code": "+232", "currency": "Sierra Leonean leone (SLL)" },
{ "name": "Singapore", "flag": "🇸🇬", "code": "SG", "dial_code": "+65", "currency": "Singapore dollar (SGD)" },
{ "name": "Slovakia", "flag": "🇸🇰", "code": "SK", "dial_code": "+421", "currency": "Euro (EUR)" },
{ "name": "Slovenia", "flag": "🇸🇮", "code": "SI", "dial_code": "+386", "currency": "Euro (EUR)" },
{ "name": "Solomon Islands", "flag": "🇸🇧", "code": "SB", "dial_code": "+677", "currency": "Solomon Islands dollar (SBD)" },
{ "name": "Somalia", "flag": "🇸🇴", "code": "SO", "dial_code": "+252", "currency": "Somali shilling (SOS)" },
{ "name": "South Africa", "flag": "🇿🇦", "code": "ZA", "dial_code": "+27", "currency": "South African rand (ZAR)" },
{ "name": "South Sudan", "flag": "🇸🇸", "code": "SS", "dial_code": "+211", "currency": "South Sudanese pound (SSP)" },
{ "name": "South Georgia and the South Sandwich Islands", "flag": "🇬🇸", "code": "GS", "dial_code": "+500", "currency": "Pound sterling (GBP)" },
{ "name": "Spain", "flag": "🇪🇸", "code": "ES", "dial_code": "+34", "currency": "Euro (EUR)" },
{ "name": "Sri Lanka", "flag": "🇱🇰", "code": "LK", "dial_code": "+94", "currency": "Sri Lankan rupee (LKR)" },
{ "name": "Sudan", "flag": "🇸🇩", "code": "SD", "dial_code": "+249", "currency": "Sudanese pound (SDG)" },
{ "name": "Suriname", "flag": "🇸🇷", "code": "SR", "dial_code": "+597", "currency": "Surinamese dollar (SRD)" },
{ "name": "Svalbard and Jan Mayen", "flag": "🇸🇯", "code": "SJ", "dial_code": "+47", "currency": "Norwegian krone (NOK)" },
{ "name": "Eswatini", "flag": "🇸🇿", "code": "SZ", "dial_code": "+268", "currency": "Swazi lilangeni (SZL)" },
{ "name": "Sweden", "flag": "🇸🇪", "code": "SE", "dial_code": "+46", "currency": "Swedish krona (SEK)" },
{ "name": "Switzerland", "flag": "🇨🇭", "code": "CH", "dial_code": "+41", "currency": "Swiss franc (CHF)" },
{ "name": "Syrian Arab Republic", "flag": "🇸🇾", "code": "SY", "dial_code": "+963", "currency": "Syrian pound (SYP)" },
{ "name": "Taiwan", "flag": "🇹🇼", "code": "TW", "dial_code": "+886", "currency": "New Taiwan dollar (TWD)" },
{ "name": "Tajikistan", "flag": "🇹🇯", "code": "TJ", "dial_code": "+992", "currency": "Somoni (TJS)" },
{ "name": "Tanzania, United Republic of Tanzania", "flag": "🇹🇿", "code": "TZ", "dial_code": "+255", "currency": "Tanzanian shilling (TZS)" },
{ "name": "Thailand", "flag": "🇹🇭", "code": "TH", "dial_code": "+66", "currency": "Thai baht (THB)" },
{ "name": "Timor-Leste", "flag": "🇹🇱", "code": "TL", "dial_code": "+670", "currency": "US dollar (USD)" },
{ "name": "Togo", "flag": "🇹🇬", "code": "TG", "dial_code": "+228", "currency": "West African CFA franc (XOF)" },
{ "name": "Tokelau", "flag": "🇹🇰", "code": "TK", "dial_code": "+690", "currency": "New Zealand dollar (NZD)" },
{ "name": "Tonga", "flag": "🇹🇴", "code": "TO", "dial_code": "+676", "currency": "Tongan paʻanga (TOP)" },
{ "name": "Trinidad and Tobago", "flag": "🇹🇹", "code": "TT", "dial_code": "+1868", "currency": "Trinidad and Tobago dollar (TTD)" },
{ "name": "Tunisia", "flag": "🇹🇳", "code": "TN", "dial_code": "+216", "currency": "Tunisian dinar (TND)" },
{ "name": "Turkey", "flag": "🇹🇷", "code": "TR", "dial_code": "+90", "currency": "Turkish lira (TRY)" },
{ "name": "Turkmenistan", "flag": "🇹🇲", "code": "TM", "dial_code": "+993", "currency": "Turkmenistani manat (TMT)" },
{ "name": "Turks and Caicos Islands", "flag": "🇹🇨", "code": "TC", "dial_code": "+1649", "currency": "US dollar (USD)" },
{ "name": "Tuvalu", "flag": "🇹🇻", "code": "TV", "dial_code": "+688", "currency": "Australian dollar (AUD)" },
{ "name": "Uganda", "flag": "🇺🇬", "code": "UG", "dial_code": "+256", "currency": "Ugandan shilling (UGX)" },
{ "name": "Ukraine", "flag": "🇺🇦", "code": "UA", "dial_code": "+380", "currency": "Hryvnia (UAH)" },
{ "name": "United Arab Emirates", "flag": "🇦🇪", "code": "AE", "dial_code": "+971", "currency": "UAE dirham (AED)" },
{ "name": "United Kingdom", "flag": "🇬🇧", "code": "GB", "dial_code": "+44", "currency": "Pound sterling (GBP)" },
{ "name": "United States", "flag": "🇺🇸", "code": "US", "dial_code": "+1", "currency": "US dollar (USD)" },
{ "name": "Uruguay", "flag": "🇺🇾", "code": "UY", "dial_code": "+598", "currency": "Uruguayan peso (UYU)" },
{ "name": "Uzbekistan", "flag": "🇺🇿", "code": "UZ", "dial_code": "+998", "currency": "Uzbekistani som (UZS)" },
{ "name": "Vanuatu", "flag": "🇻🇺", "code": "VU", "dial_code": "+678", "currency": "Vanuatu vatu (VUV)" },
{ "name": "Venezuela, Bolivarian Republic of Venezuela", "flag": "🇻🇪", "code": "VE", "dial_code": "+58", "currency": "Venezuelan bolívar (VES)" },
{ "name": "Vietnam", "flag": "🇻🇳", "code": "VN", "dial_code": "+84", "currency": "Vietnamese đồng (VND)" },
{ "name": "Virgin Islands, British", "flag": "🇻🇬", "code": "VG", "dial_code": "+1284", "currency": "US dollar (USD)" },
{ "name": "Virgin Islands, U.S.", "flag": "🇻🇮", "code": "VI", "dial_code": "+1340", "currency": "US dollar (USD)" },
{ "name": "Wallis and Futuna", "flag": "🇼🇫", "code": "WF", "dial_code": "+681", "currency": "CFP franc (XPF)" },
{ "name": "Yemen", "flag": "🇾🇪", "code": "YE", "dial_code": "+967", "currency": "Yemeni rial (YER)" },
{ "name": "Zambia", "flag": "🇿🇲", "code": "ZM", "dial_code": "+260", "currency": "Zambian kwacha (ZMW)" },
{ "name": "Zimbabwe", "flag": "🇿🇼", "code": "ZW", "dial_code": "+263", "currency": "Zimbabwean dollar (ZWL)" },
]
export default countries;